import { test, expect } from '@playwright/test';

test.only('this was generated by codegen', async ({ page }) => {
  await page.goto('https://the-internet.herokuapp.com/login');
  await page.pause();
  await page.getByRole('textbox', { name: 'Username' }).fill('tomsmith');
  await page.getByRole('textbox', { name: 'Password' }).fill('SuperSecretPassword!');
  await page.getByRole('button', { name: ' Login' }).click();
  await expect(page.getByText('You logged into a secure area')).toBeVisible();
  await expect(page.locator('#content')).toContainText('Secure Area Welcome to the Secure Area. When you are done click logout below. Logout');
  await page.getByRole('link', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('11');
  await expect(page.getByRole('textbox', { name: 'Username' })).toHaveValue('11');
  await page.pause();
});